const mockData = [
    {
        id: "1",
        title: "Gestión de remiserías",
        description: "Sistema de gestión para remiserías",
        price: "10500",
        pictureUrl: 'agencia.jpg',
        stock: 5,
    },
    {
        id: "2",
        title: "Gestión de flotas",
        description: "Sistema de gestión para mantenimiento de vehículos",
        price: "10500",
        pictureUrl: 'mant.jpg',
        stock: 5,
    },
    {
        id: "3",
        title: "Gestión de mensajerías",
        description: "Sistema de gestión para motomensajerías y logística",
        price: "10500",
        pictureUrl: 'mens.jpg',
        stock: 5,
    },
    {
        id: "4",
        title: "Gestión de peluquerías",
        description: "Sistema de gestión para peluquerías y salones de belleza",
        price: "10500",
        pictureUrl: 'pelu.jpg',
        stock: 5,
    },
    {
        id: "5",
        title: "Gestión de PetShop",
        description: "Sistema de gestión para petshop y peluquería canina",
        price: "10500",
        pictureUrl: 'pet.jpg',
        stock: 5,
    },
    {
        id: "6",
        title: "Gestión de gestorías",
        description: "Sistema de gestión para gestorías",
        price: "10500",
        pictureUrl: 'pgestion.jpg',
        stock: 5,
    },
    {
        id: "7",
        title: "Gestión de préstamos",
        description: "Sistema de gestión para prestamistas y financieras",
        price: "10500",
        pictureUrl: 'prest.jpg',
        stock: 5,
    },
    {
        id: "8",
        title: "Presupuestos y remitos",
        description: "Sistema simple para generar presupuestos y remitos personalizados",
        price: "3600",
        pictureUrl: 'presu.jpg',
        stock: 5,
    },
    {
        id: "9",
        title: "Prontas Ventas",
        description: "Punto de venta multi rubro para gestionar comercios",
        price: "5900",
        pictureUrl: 'pventas.jpg',
        stock: 5,
    },
];

export { mockData };